openapi: 3.0.0
info:
  title: Super Heros Bio Data SAPI
  description: Super-Bio-SAPI allows you to fetch the basic bio-data of various super heros.
  version: "1.0"

servers:
  - url: https://super-biodata-sapi-2s24tv.5sc6y6-2.usa-e2.cloudhub.io/api

components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic

paths:
  /bio/{id}:
    get:
      operationId: getBioById  # Required by watsonx
      # 🧠 REMOVE summary & description at path level to avoid duplication
      security:
        - basicAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            example: DC0003
      responses:
        '200':
          description: Bio data found
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    example: DC0003
                  name:
                    type: string
                    example: Wonder Woman
                  alias:
                    type: string
                    example: Diana Prince
                  origin:
                    type: string
                    example: Themyscira
                  powers:
                    type: array
                    items:
                      type: string
                    example: [ "Super strength", "Agility", "Flight" ]
