#%RAML 1.0 NamedExample
_id: 
  $oid:  "61f4e481ab7feb3fbd1d25a4"
id: "DC0002"
name: "Wonder Woman"
fullname: "Diana Prince"
birthplace: "Themyscira"
base: "-"
publisher: "DC Comics"
occupation: "Protector of Paradise Island; former Goddess of Truth"