#%RAML 1.0
title: Super Heros Bio Data SAPI
description: Super-Bio-SAPI allows you to fetch the basic bio-data of various super heros.
version: 1.0
mediaType: application/json

types:
  bio-data: !include types/bioData_dataType.raml

securitySchemes:
  basic-auth: !include exchange_modules/org.mule.examples/basic-auth-securityscheme/1.0.0/basic-auth-securityscheme.raml

securedBy: basic-auth

/bio/{id}:
  uriParameters:
    id:
      required: true
      example:
        value: DC0003
  get:
   displayName: Get BioData by CID
   description: This resources fetches bio data based on the unique **id** sent in the URI Parameter 
   responses:
     200:
       description: If **id** exists, returns the bio data
       body:
         application/json:
           type: bio-data
           example: !include examples/bioData_example.raml